# Header
menu:
  Home: /
  Archives: /archives
  'Fork Me': https://github.com/cishenn/cishenn.github.io

# Content
excerpt_link: More
prev: Prev
next: Next
reply: Reply
share: Share
fancybox: true

# Sidebar
widgets:
- search
- music
- category
- recent_posts
- tag
- tagcloud
- stats

# Miscellaneous
google_analytics:
duoshuo_shortname: 
rss: 
google_site_verification: 
baidu_site_verification: 
favicon: 
music: /assets/victoria.mp3

#busuanzi
busuanzi:
 enable: true